//! Build script: embed the `config/vendors/*.json` vendor registry into the binary.
//!
//! The vendor registry (219 curated vendor definitions), the known-vendors database, and the
//! SaaS-platforms list all used to load from a `config/` directory relative to the working
//! directory. A binary installed by Homebrew / crates.io / Docker / a raw tarball ships no such
//! directory, so those runs silently degraded to an empty registry ("using empty registry",
//! "Failed to load SaaS platforms: No such file or directory"). Single files are embedded directly
//! with `include_str!` in their modules; the *directory* of vendor files is embedded here because
//! `include_str!` needs one literal path per file — this generates those literals from whatever is
//! on disk at build time, so adding/removing a vendor JSON needs no code change.
//!
//! A user-provided `config/vendors/` directory still wins at runtime (see `vendor_registry::init`);
//! this is only the default when none is found.

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let vendors_dir = PathBuf::from(&manifest_dir).join("config").join("vendors");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", vendors_dir.display());

    let read_dir = std::fs::read_dir(&vendors_dir)
        .unwrap_or_else(|e| panic!("build.rs: cannot read {}: {e}", vendors_dir.display()));

    // Collect (file_name, absolute_path) for every embeddable vendor JSON. Mirror the runtime
    // filter used by `filter_vendor_path`: only `.json`, and never the `_schema.json` sidecar.
    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    for entry in read_dir {
        let path = entry.expect("build.rs: readable dir entry").path();
        let is_json = path.extension().map(|e| e == "json").unwrap_or(false);
        let name = match path.file_name() {
            Some(n) => n.to_string_lossy().into_owned(),
            None => continue,
        };
        if is_json && name != "_schema.json" {
            // Re-run the build if any embedded file's *content* changes (a directory
            // rerun-if-changed only catches additions/removals on some platforms).
            println!("cargo:rerun-if-changed={}", path.display());
            entries.push((name, path));
        }
    }
    // Deterministic order so the generated file (and thus the build) is reproducible.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::new();
    code.push_str("// @generated by build.rs — do not edit. Embeds config/vendors/*.json.\n");
    code.push_str("pub static EMBEDDED_VENDOR_FILES: &[(&str, &str)] = &[\n");
    for (name, path) in &entries {
        // `{:?}` emits a valid Rust string literal (escaping quotes/backslashes), so this is
        // correct on Windows paths too.
        writeln!(
            code,
            "    ({:?}, include_str!({:?})),",
            name,
            path.to_string_lossy()
        )
        .expect("write to String is infallible");
    }
    code.push_str("];\n");

    let dest = PathBuf::from(&out_dir).join("embedded_vendors.rs");
    std::fs::write(&dest, code)
        .unwrap_or_else(|e| panic!("build.rs: cannot write {}: {e}", dest.display()));
}
