coverage:
  precision: 2
  round: down
  range: "60...90"
  status:
    project:
      default:
        target: 60%
        threshold: 5%
    patch:
      default:
        target: 70%

ignore:
  - "src/main.rs"
  - "tests/**/*"
  - "examples/**/*"
