#!/usr/bin/env bun
/*
 * build-design-system-css.ts
 *
 * Assembles a SINGLE self-contained stylesheet for the nthpartyfinder HTML report
 * from the GRC Engineering Design System (github.com/grcengineering/grce-design-system).
 *
 *   - inlines the token layers (colors, typography, spacing, effects, motion, base)
 *   - base64-embeds the 5 variable woff2 fonts as data: URIs (no external fetch)
 *
 * Output: static/design-system.css  (committed; the Rust build include_str!s it,
 * so `cargo build` never needs the sibling repo — only regeneration does).
 *
 * Re-run after re-syncing the design system from Claude Design (see SYNC.md there):
 *   bun scripts/build-design-system-css.ts [path-to-grce-design-system]
 *
 * bun-only (no npm). TypeScript per project rules.
 */
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoStatic = resolve(scriptDir, "..", "static");
const DS = resolve(scriptDir, Bun.argv[2] ?? "../../../grce-design-system");

// Token layers, in cascade order. fonts.css is replaced by inlined @font-face below.
const TOKEN_LAYERS = ["colors", "typography", "spacing", "effects", "motion", "base"];

// (family, file, weightRange, style) — mirrors tokens/fonts.css exactly, url()->data:
const FONT_FACES: Array<{ family: string; file: string; weight: string; style: string }> = [
  { family: "General Sans", file: "general-sans-vf.woff2", weight: "400 700", style: "normal" },
  { family: "Satoshi", file: "satoshi-vf.woff2", weight: "300 900", style: "normal" },
  { family: "Satoshi", file: "satoshi-vf-italic.woff2", weight: "300 900", style: "italic" },
  { family: "Archivo", file: "archivo-vf.woff2", weight: "400 800", style: "normal" },
  { family: "Martian Mono", file: "martian-mono-vf.woff2", weight: "400 700", style: "normal" },
];

async function readText(p: string): Promise<string> {
  const f = Bun.file(p);
  if (!(await f.exists())) throw new Error(`missing source file: ${p}`);
  return f.text();
}

async function fontDataUri(file: string): Promise<string> {
  const p = resolve(DS, "assets/fonts", file);
  const f = Bun.file(p);
  if (!(await f.exists())) throw new Error(`missing font: ${p}`);
  const b64 = Buffer.from(await f.arrayBuffer()).toString("base64");
  return `data:font/woff2;base64,${b64}`;
}

async function main() {
  console.log(`source design system: ${DS}`);
  const parts: string[] = [];
  parts.push(
    `/* AUTO-GENERATED by scripts/build-design-system-css.ts — DO NOT EDIT BY HAND.\n` +
      `   Source: GRC Engineering Design System (grcengineering/grce-design-system).\n` +
      `   Self-contained: token layers inlined + fonts base64-embedded. */\n`,
  );

  // 1) @font-face with embedded woff2 (replaces tokens/fonts.css)
  const faces: string[] = ["\n/* ===== self-hosted fonts (base64-embedded) ===== */"];
  for (const ff of FONT_FACES) {
    const uri = await fontDataUri(ff.file);
    faces.push(
      `@font-face{font-family:"${ff.family}";src:url("${uri}") format("woff2");` +
        `font-weight:${ff.weight};font-style:${ff.style};font-display:swap;}`,
    );
  }
  parts.push(faces.join("\n"));

  // 2) token layers
  for (const layer of TOKEN_LAYERS) {
    const css = await readText(resolve(DS, "tokens", `${layer}.css`));
    parts.push(`\n/* ===== tokens/${layer}.css ===== */\n${css.trim()}`);
  }

  const out = parts.join("\n") + "\n";
  const outPath = resolve(repoStatic, "design-system.css");
  await Bun.write(outPath, out);

  // sanity checks
  const kib = (out.length / 1024).toFixed(1);
  const hasOrange = out.includes("--grc-orange-400");
  const hasBlue = out.includes("--eng-blue-500");
  const hasFusion = out.includes("--gradient-fusion");
  const faceCount = (out.match(/@font-face/g) ?? []).length;
  console.log(`wrote ${outPath} (${kib} KiB)`);
  console.log(`checks: @font-face=${faceCount}/5  orange=${hasOrange}  blue=${hasBlue}  fusion=${hasFusion}`);
  if (faceCount !== 5 || !hasOrange || !hasBlue || !hasFusion) {
    console.error("SANITY CHECK FAILED");
    process.exit(1);
  }
}

await main();
